Adding upstream version 1.154.1.

diff --git a/scripts/live b/scripts/live
--- a/scripts/live
+++ b/scripts/live
@@ -21,6 +21,17 @@ HOSTNAME="host"
 
 mkdir -p "${mountpoint}"
 
+# Create /etc/mtab for debug purpose and future syncs
+if [ ! -d /etc ]
+then
+	mkdir /etc/
+fi
+
+if [ ! -f /etc/mtab ]
+then
+	touch /etc/mtab
+fi
+
 [ -f /etc/live.conf ] && . /etc/live.conf
 export USERNAME USERFULLNAME HOSTNAME
 
@@ -275,9 +286,9 @@ Arguments ()
 				export NOPROGRAMCRASHES
 				;;
 
-			norestrictedmanager)
-				NORESTRICTEDMANAGER="Yes"
-				export NORESTRICTEDMANAGER
+			nojockey)
+				NOJOCKEY="Yes"
+				export NOJOCKEY
 				;;
 
 			nosudo)
@@ -285,9 +296,9 @@ Arguments ()
 				export NOSUDO
 				;;
 
-			noswap)
-				NOSWAP="Yes"
-				export NOSWAP
+			swapon)
+				SWAPON="Yes"
+				export SWAPON
 				;;
 
 			noupdatenotifier)
@@ -315,6 +326,15 @@ Arguments ()
 				export PERSISTENT
 				;;
 
+			persistent=*)
+				PERSISTENT="${ARGUMENT#persistent=}"
+				if [ -z "${PERSISTENT}" ]
+				then
+					PERSISTENT="Yes"
+				fi
+				export PERSISTENT
+				;;
+
 			nopersistent)
 				NOPERSISTENT="Yes"
 				export NOPERSISTENT
@@ -333,9 +353,9 @@ Arguments ()
 			url=*)
 				location="${ARGUMENT#url=}"
 
-				mount -n -o bind /sys /root/sys
-				mount -n -o bind /proc /root/proc
-				mount -n -o bind /dev /root/dev
+				mount -o bind /sys /root/sys
+				mount -o bind /proc /root/proc
+				mount -o bind /dev /root/dev
 
 				mkdir -p /root/var/run/network
 				chroot /root dhclient eth0
@@ -489,7 +509,7 @@ matches_uuid ()
 	path="${1}"
 	uuid="$(cat /conf/uuid.conf)"
 
-	for try_uuid_file in "${mountpoint}/.disk/live-uuid"*
+	for try_uuid_file in "${path}/.disk/live-uuid"*
 	do
 		[ -e "${try_uuid_file}" ] || continue
 
@@ -538,7 +558,7 @@ mount_images_in_directory ()
 {
 	directory="${1}"
 	rootmnt="${2}"
-    	mac="${3}"
+	mac="${3}"
 
 
 	if match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.squashfs" ||
@@ -550,7 +570,7 @@ mount_images_in_directory ()
 		[ -n "${mac}" ] && adddirectory="${directory}/${LIVE_MEDIA_PATH}/${mac}"
 		setup_unionfs "${directory}/${LIVE_MEDIA_PATH}" "${rootmnt}" "${adddirectory}"
 	else
-		:
+		panic "No supported filesystem images found at /${LIVE_MEDIA_PATH}."
 	fi
 }
 
@@ -558,7 +578,7 @@ is_nice_device ()
 {
 	sysfs_path="${1#/sys}"
 
-	if /lib/udev/path_id "${sysfs_path}" | grep -E -q "ID_PATH=(usb|pci-[^-]*-[ide|scsi|usb])"
+	if /lib/udev/path_id "${sysfs_path}" | grep -E -q "ID_PATH=(usb|pci-[^-]*-(ide|scsi|usb))"
 	then
 		return 0
 	elif echo "${sysfs_path}" | grep -q '^/block/vd[a-z]$'
@@ -593,7 +613,7 @@ copy_live_to ()
 	if [ "${copytodev}" = "ram" ]
 	then
 		# copying to ram:
-		freespace=$( expr $(awk '/MemFree/{print $2}' /proc/meminfo) + $( cat /proc/meminfo | grep Cached | head -n 1 | awk '/Cached/{print $2}' - ) )
+		freespace=$( expr $(awk '/MemFree/{print $2}' /proc/meminfo) + $( awk '/\<Cached/{print $2}' /proc/meminfo ) )
 		mount_options="-o size=${size}k"
 		free_string="memory"
 		fstype="tmpfs"
@@ -621,14 +641,14 @@ copy_live_to ()
 	# begin copying (or uncompressing)
 	mkdir "${copyto}"
 	echo "mount -t ${fstype} ${mount_options} ${dev} ${copyto}"
-	mount -n -t "${fstype}" ${mount_options} "${dev}" "${copyto}"
+	mount -t "${fstype}" ${mount_options} "${dev}" "${copyto}"
 
 	if [ "${extension}" = "tgz" ]
 	then
 		cd "${copyto}"
 		tar zxf "${copyfrom}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
 		rm -f "${copyfrom}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
-		mount -n -r -o move "${copyto}" "${rootmnt}"
+		mount -r -o move "${copyto}" "${rootmnt}"
 		cd "${OLDPWD}"
 	else
 		if [ -n "${MODULETORAMFILE}" ]
@@ -638,9 +658,8 @@ copy_live_to ()
 			cp -a ${copyfrom}/* ${copyto}   # "cp -a" from busybox also copies hidden files
 		fi
 
-		livefs_root
 		umount ${copyfrom}
-		mount -n -r -o move ${copyto} ${copyfrom}
+		mount -r -o move ${copyto} ${copyfrom}
 	fi
 
 	rmdir ${copyto}
@@ -671,6 +690,15 @@ do_netmount ()
 	. /tmp/net-${DEVICE}.conf
 	[ -z ${HOSTNAME} ] && HOSTNAME=${OLDHOSTNAME}
 	export HOSTNAME
+
+	# Check if we have a network device at all
+	if ! ls /sys/class/net/eth0 > /dev/null 2>&1 && \
+	   ! ls /sys/class/net/wlan0 > /dev/null 2>&1 && \
+	   ! ls /sys/class/net/ath0 > /dev/null 2>&1 && \
+	   ! ls /sys/class/net/ra0 > /dev/null 2>&1
+	then
+		panic "No supported network device found, maybe a non-mainline driver is required."
+	fi
 
 	if [ "${NFSROOT}" = "auto" ]
 	then
@@ -708,7 +736,7 @@ do_httpmount ()
 {
 	rc=1
 	dest="${mountpoint}/${LIVE_MEDIA_PATH}"
-	mount -n -t ramfs ram "${mountpoint}"
+	mount -t ramfs ram "${mountpoint}"
 	mkdir -p "${dest}"
 
 	for webfile in HTTPFS FTPFS FETCH
@@ -779,11 +807,13 @@ do_nfsmount ()
 
 	log_begin_msg "Trying nfsmount -o nolock -o ro ${NFSOPTS} ${NFSROOT} ${mountpoint}"
 
-	# FIXME: This for loop is an ugly HACK round an nfs bug
-	for i in 0 1 2 3 4 5 6 7 8 9 a b c d e f 10 11 12 13
+	# FIXME: This while loop is an ugly HACK round an nfs bug
+	i=0
+	while [ "$i" -lt 60 ]
 	do
 		nfsmount -o nolock -o ro ${NFSOPTS} "${NFSROOT}" "${mountpoint}" && rc=0 && break
 		sleep 1
+		i="$(($i + 1))"
 	done
 
 	return ${rc}
@@ -826,10 +856,10 @@ do_snap_copy ()
 		# look for free mem
 		if [ -n "${HOMEMOUNTED}" -a "${snap_type}" = "HOME" ]
 		then
-			todev=$(cat /proc/mounts | grep -s " $(base_path ${todir}) " | awk '{print $1}' )
-			freespace=$(df -k  | grep -s ${todev} | awk '{print $4}')
+			todev=$(awk -v pat="$(base_path ${todir})" '$2 == pat { print $1 }' /proc/mounts)
+			freespace=$(df -k | awk '/'${todev}'/{print $4}')
 		else
-			freespace=$( expr $(awk '/MemFree/{print $2}' /proc/meminfo) + $( cat /proc/meminfo | grep Cached | head -n 1 | awk '/Cached/{print $2}' - ))
+			freespace=$( expr $(awk '/MemFree/{print $2}' /proc/meminfo) + $( awk '/\<Cached/{print $2}' /proc/meminfo))
 		fi
 
 		tomount="/mnt/tmpsnap"
@@ -844,7 +874,7 @@ do_snap_copy ()
 		if [ -n "${fstype}" ]
 		then
 			# Copying stuff...
-			mount -n -t "${fstype}" -o ro,noatime "${fromdev}" "${tomount}"
+			mount -o ro -t "${fstype}" "${fromdev}" "${tomount}" || log_warning_msg "Error in mount -t ${fstype} -o ro ${fromdev} ${tomount}"
 			cp -a "${tomount}"/* ${todir}
 			umount "${tomount}"
 		else
@@ -866,72 +896,102 @@ do_snap_copy ()
 	fi
 }
 
+find_snap ()
+{
+	# Look for ${snap_label}.* in block devices
+	snap_label="${1}"
+
+	if [ "${PERSISTENT}" != "nofiles" ]
+	then
+		# search for image files
+		snapdata=$(find_files "${snap_label}.squashfs ${snap_label}.cpio.gz ${snap_label}.ext2 ${snap_label}.ext3 ${snap_label}.jffs2")
+	fi
+
+	if [ -z "${snapdata}" ]
+	then
+		snapdata=$(find_cow_device "${snap_label}")
+	fi
+	echo "${snapdata}"
+}
+
 try_snap ()
 {
-	# Look for ${snap_label}.* in block devices and copy the contents to ${snap_mount}
+        # copy the contents of previously found snapshot to ${snap_mount}
 	# and remember the device and filename for resync on exit in live-initramfs.init
 
-	snap_label="${1}"
+	snapdata="${1}"
 	snap_mount="${2}"
 	snap_type="${3}"
-	snapdata=$(find_files "${snap_label}.squashfs ${snap_label}.cpio.gz ${snap_label}.ext2 ${snap_label}.ext3 ${snap_label}.jffs2")
 
 	if [ ! -z "${snapdata}" ]
 	then
+		log_success_msg "found snapshot: ${snapdata}"
 		snapdev="$(echo ${snapdata} | cut -f1 -d ' ')"
 		snapback="$(echo ${snapdata} | cut -f2 -d ' ')"
 		snapfile="$(echo ${snapdata} | cut -f3 -d ' ')"
+
+		RES=""
+		if ! try_mount "${snapdev}" "${snapback}" "ro"
+		then
+			break
+		fi
 
 		if echo "${snapfile}" | grep -qs '\(squashfs\|ext2\|ext3\|jffs2\)'
 		then
 			# squashfs, jffs2 or ext2/ext3 snapshot
 			dev=$(get_backing_device "${snapback}/${snapfile}")
 
-			if ! do_snap_copy "${dev}" "${snap_mount}" "${snap_type}"
-			then
-				log_warning_msg "Impossible to include the ${snapfile} Snapshot"
-				return 1
-			fi
+			do_snap_copy "${dev}" "${snap_mount}" "${snap_type}"
+			RES=$?
 		else
 			# cpio.gz snapshot
-			if ! (cd "${snap_mount}" && zcat "${snapback}/${snapfile}" | cpio --extract --preserve-modification-time --no-absolute-filenames --sparse --unconditional --make-directories > /dev/null 2>&1)
+			cd "${snap_mount}"
+			zcat "${snapback}/${snapfile}" | /bin/cpio --extract --preserve-modification-time --no-absolute-filenames --sparse --unconditional --make-directories > /dev/null 2>&1
+			RES=$?
+			if [ "${RES}" != "0" ]
 			then
-				log_warning_msg "Impossible to include the ${snapfile} Snapshot"
-				return 1
+				log_warning_msg "failure to \"zcat ${snapback}/${snapfile} | /bin/cpio --extract --preserve-modification-time --no-absolute-filenames --sparse --unconditional --make-directories\""
 			fi
+			cd "${OLDPWD}"
 		fi
 
-		umount "${snapback}"
-	else
-		dev=$(find_cow_device "${snap_label}")
+		umount "${snapback}" ||  log_warning_msg "failure to \"umount ${snapback}\""
 
-		if [ -b ${dev} ]
+		if [ "${RES}" != "0" ]
 		then
-			if echo "${dev}" | grep -qs loop
-			then
-				# strange things happens, user confused?
-				snaploop=$( losetup ${dev} | awk '{print $3}' | tr -d '()' )
-				snapfile=$(basename ${snaploop})
-				snapdev=$(cat /proc/mounts | awk '{print $2,$1}' | grep -es "^$( dirname ${snaploop} )" | cut -f2 -d ' ')
-			else
-				snapdev="${dev}"
-			fi
-
-			if ! do_snap_copy "${dev}" "${snap_mount}" "${snap_type}"
-			then
-				log_warning_msg "Impossible to include the ${snap_label} Snapshot"
-				return 1
-			else
-				if [ -n "${snapfile}" ]
-				then
-					# it was a loop device, user confused
-					umount ${snapdev}
-				fi
-			fi
-		else
-			log_warning_msg "Impossible to include the ${snap_label} Snapshot"
-			return 1
+			log_warning_msg "Impossible to include the ${snapfile} Snapshot file"
 		fi
+
+
+	elif [ -b "${snapdata}" ]
+	then
+		# Try to find if it could be a snapshot partition
+		dev="${snapdata}"
+		log_success_msg "found snapshot device on ${dev}"
+		if echo "${dev}" | grep -qs loop
+		then
+			# strange things happens, user confused?
+			snaploop=$( losetup ${dev} | awk '{print $3}' | tr -d '()' )
+			snapfile=$(basename ${snaploop})
+			snapdev=$(awk -v pat="$( dirname ${snaploop})" '$2 == pat { print $1 }' /proc/mounts)
+		else
+			snapdev="${dev}"
+		fi
+
+		if ! do_snap_copy "${dev}" "${snap_mount}" "${snap_type}"
+		then
+			log_warning_msg "Impossible to include the ${snap_type} Snapshot"
+			return 1
+		else
+			if [ -n "${snapfile}" ]
+			then
+				# it was a loop device, user confused
+				umount ${snapdev}
+			fi
+		fi
+	else
+		log_warning_msg "Impossible to include the ${snap_type} Snapshot"
+		return 1
 	fi
 
 	echo "export ${snap_type}SNAP="${snap_mount}":${snapdev}:${snapfile}" >> /etc/live.conf # for resync on reboot/halt
@@ -1040,9 +1100,15 @@ setup_unionfs ()
 				panic "Unknown file system type on ${backdev} (${image})"
 			fi
 
+			if [ -z "${fstype}" ]
+			then
+				fstype="${imagename##*.}"
+				log_warning_msg "Unknown file system type on ${backdev} (${image}), assuming ${fstype}."
+			fi
+
 			mkdir -p "${croot}/${imagename}"
 			log_begin_msg "Mounting \"${image}\" on \"${croot}${imagename}\" via \"${backdev}\""
-			mount -n -t "${fstype}" -o ro,noatime "${backdev}" "${croot}/${imagename}" || panic "Can not mount ${backdev} (${image}) on ${croot}/${imagename}" && rofsstring="${croot}/${imagename}=${roopt}:${rofsstring}" && rofslist="${croot}/${imagename} ${rofslist}"
+			mount -t "${fstype}" -o ro,noatime "${backdev}" "${croot}/${imagename}" || panic "Can not mount ${backdev} (${image}) on ${croot}/${imagename}" && rofsstring="${croot}/${imagename}=${roopt}:${rofsstring}" && rofslist="${croot}/${imagename} ${rofslist}"
 			log_end_msg
 		fi
 	done
@@ -1086,7 +1152,30 @@ setup_unionfs ()
 			fi
 		done
 
+		# search for label and files (this could be hugely optimized)
 		cowprobe=$(find_cow_device "${root_persistence}")
+		if [ -b "${cowprobe}" ]
+		then
+			# Blacklist /cow device, to avoid inconsistent setups for overlapping snapshots
+			# makes sense to have both persistence for /cow and /home mounted, maybe also with
+			# snapshots to be sure to really store some e.g key config files,
+			# but not on the same media
+			blacklistdev="${cowprobe}"
+			PERSISTENCE_IS_ON="1"
+			export PERSISTENCE_IS_ON
+		fi
+		# homecow just mount something on /home, this should be generalized some way
+		homecow=$(find_cow_device "${home_persistence}" "${blacklistdev}")
+		if [ -b "${homecow}" ]
+		then
+			PERSISTENCE_IS_ON="1"
+			export PERSISTENCE_IS_ON
+		fi
+		root_snapdata=$(find_snap "${root_snapshot_label}" "${blacklistdev}")
+		# This second type should be removed when snapshot will get smarter,
+		# hence when "/etc/live-snapshot*list" will be supported also by
+		# ext2|ext3|jffs2 snapshot types.
+		home_snapdata=$(find_snap "${home_snapshot_label}" "${blacklistdev}")
 
 		if [ -b "${cowprobe}" ]
 		then
@@ -1131,7 +1220,7 @@ setup_unionfs ()
 		nfsmount ${nfs_cow_opts} ${cowdevice} /cow || \
 			panic "Can not mount ${cowdevice} (n: ${cow_fstype}) on /cow"
 	else
-		mount -n -t ${cow_fstype} -o ${cow_mountopt} ${cowdevice} /cow || \
+		mount -t ${cow_fstype} -o ${cow_mountopt} ${cowdevice} /cow || \
 			panic "Can not mount ${cowdevice} (o: ${cow_fstype}) on /cow"
 	fi
 
@@ -1145,7 +1234,7 @@ setup_unionfs ()
 		fi
 		exposedrootfs=${rofslist%% }
 
-		mount -n --bind ${exposedrootfs} ${rootmnt} || \
+		mount --bind ${exposedrootfs} ${rootmnt} || \
 			panic "bind mount of ${exposedrootfs} failed"
 
 		cow_dirs='/var/tmp /var/lock /var/run /var/log /var/spool
@@ -1153,14 +1242,14 @@ setup_unionfs ()
 
 		for dir in ${cow_dirs}; do
 			mkdir -p /cow${dir}
-			mount -n -t ${UNIONTYPE} \
+			mount -t ${UNIONTYPE} \
 				-o rw,noatime,dirs=/cow${dir}=rw:${exposedrootfs}${dir}=ro \
 				${UNIONTYPE} "${rootmnt}${dir}" || \
 				panic "mount ${UNIONTYPE} on ${rootmnt}${dir} failed with option \
 					rw,noatime,dirs=/cow${dir}=rw:${exposedrootfs}${dir}=ro"
 		done
 	else
-		mount -n -t ${UNIONTYPE} -o noatime,dirs=/cow=rw:${rofsstring} \
+		mount -t ${UNIONTYPE} -o noatime,dirs=/cow=rw:${rofsstring} \
 			${UNIONTYPE} "${rootmnt}" || panic "mount ${UNIONTYPE} on \
 			${rootmnt} failed with option noatime,dirs=/cow=rw:${rofsstring}"
 	fi
@@ -1168,26 +1257,26 @@ setup_unionfs ()
 	# tmpfs file systems
 	touch /etc/fstab
 	mkdir -p "${rootmnt}/live"
-	mount -n -t tmpfs tmpfs ${rootmnt}/live
+	mount -t tmpfs tmpfs ${rootmnt}/live
 
 	# Adding other custom mounts
 	if [ -n "${PERSISTENT}" ] && [ -z "${NOPERSISTENT}" ]
 	then
 		# directly mount /home
 		# FIXME: add a custom mounts configurable system
-		homecow=$(find_cow_device "${home_persistence}" )
 
 		if [ -b "${homecow}" ]
 		then
-			mount -n -t $(get_fstype "${homecow}") -o rw,noatime "${homecow}" "${rootmnt}/home"
+			mount -t $(get_fstype "${homecow}") -o rw,noatime "${homecow}" "${rootmnt}/home"
 			export HOMEMOUNTED=1 # used to proper calculate free space in do_snap_copy()
 		else
 			log_warning_msg "Unable to find the persistent home medium"
 		fi
 
 		# Look for other snapshots to copy in
-		try_snap "${root_snapshot_label}" "${rootmnt}" "ROOT"
-		try_snap "${home_snapshot_label}" "${rootmnt}/home" "HOME"
+		try_snap "${root_snapdata}" "${rootmnt}" "ROOT"
+		# This second type should be removed when snapshot grow smarter
+		try_snap "${home_snapdata}" "${rootmnt}/home" "HOME"
 	fi
 
 	if [ -n "${SHOWMOUNTS}" ]
@@ -1202,7 +1291,7 @@ setup_unionfs ()
 					;;
 
 				*)
-					mount -n -o move "${d}" "${rootmnt}/live/${d##*/}"
+					mount -o move "${d}" "${rootmnt}/live/${d##*/}"
 					;;
 			esac
 		done
@@ -1210,7 +1299,7 @@ setup_unionfs ()
 
 	# shows cow fs on /cow for use by live-snapshot
 	mkdir -p "${rootmnt}/live/cow"
-	mount -n -o move /cow "${rootmnt}/live/cow" >/dev/null 2>&1 || mount -n -o bind /cow "${rootmnt}/live/cow" || log_warning_msg "Unable to move or bind /cow to ${rootmnt}/live/cow"
+	mount -o move /cow "${rootmnt}/live/cow" >/dev/null 2>&1 || mount -o bind /cow "${rootmnt}/live/cow" || log_warning_msg "Unable to move or bind /cow to ${rootmnt}/live/cow"
 }
 
 check_dev ()
@@ -1226,7 +1315,7 @@ check_dev ()
 
 	if [ -d "${devname}" ]
 	then
-		mount -n -o bind "${devname}" $mountpoint || continue
+		mount -o bind "${devname}" $mountpoint || continue
 
 		if is_live_path $mountpoint
 		then
@@ -1247,7 +1336,7 @@ check_dev ()
 
 	if is_supported_fs ${fstype}
 	then
-		mount -n -t ${fstype} -o ro,noatime "${devname}" ${mountpoint} || continue
+		mount -t ${fstype} -o ro,noatime "${devname}" ${mountpoint} || continue
 
 		if is_live_path ${mountpoint} && \
 			([ "${skip_uuid_check}" ] || matches_uuid ${mountpoint})
@@ -1290,7 +1379,7 @@ find_livefs ()
 	fi
 
 	# or do the scan of block devices
-	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v 'dm-' | grep -v fd )
+	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -vE "/(loop|ram|dm-|fd)")
 	do
 		devname=$(sys2dev "${sysblock}")
 		fstype=$(get_fstype "${devname}")
@@ -1332,12 +1421,13 @@ set_usplash_timeout ()
 	if [ -x /sbin/usplash_write ]
 	then
 		/sbin/usplash_write "TIMEOUT 120"
-	fi
+	else if [ -x /sbin/splashy_update ] ; then
+		/sbin/splashy_update "TIMEOUT 120"
+	fi ; fi
 }
 
 mountroot ()
 {
-    
         if [ -x /scripts/local-top/cryptroot ]; then
 	    /scripts/local-top/cryptroot
 	fi
@@ -1350,11 +1440,13 @@ mountroot ()
 	tailpid="${!}"
 
 	# Ensure 'panic' function is overridden
-    	. /scripts/live-functions
+	. /scripts/live-functions
 
 	Arguments
 
 	set_usplash_timeout
+
+	maybe_break live-premount
 	log_begin_msg "Running /scripts/live-premount"
 	run_scripts /scripts/live-premount
 	log_end_msg
@@ -1379,7 +1471,8 @@ mountroot ()
 			livefs_root=${ROOT}
 		else
 			# Scan local devices for the image
-			for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
+			i=0
+			while [ "$i" -lt 60 ]
 			do
 				livefs_root=$(find_livefs ${i})
 
@@ -1389,6 +1482,7 @@ mountroot ()
 				fi
 
 				sleep 1
+				i="$(($i + 1))"
 			done
 		fi
 	fi
diff --git a/scripts/live-helpers b/scripts/live-helpers
--- a/scripts/live-helpers
+++ b/scripts/live-helpers
@@ -77,7 +77,7 @@ get_fstype ()
 	    return
 	fi
 
-	eval $(fstype < ${1})
+	eval $(fstype < ${1} 2>/dev/null)
 
 	if [ "${FSTYPE}" != "unknown" ]
 	then
@@ -146,7 +146,7 @@ fs_size ()
 			mountp="/mnt/tmp_fs_size"
 
 			mkdir -p "${mountp}"
-			mount -n -t $(get_fstype "${dev}") -o ro "${dev}" "${mountp}"
+			mount -t $(get_fstype "${dev}") -o ro "${dev}" "${mountp}" || log_warning_msg "cannot mount -t $(get_fstype ${dev}) -o ro ${dev} ${mountp}"
 
 			doumount=1
 		fi
@@ -163,7 +163,7 @@ fs_size ()
 
 	if [ -n "${doumount}" ]
 	then
-		umount "${mountp}"
+		umount "${mountp}" || log_warning_msg "cannot umount ${mountp}"
 		rmdir "${mountp}"
 	fi
 
@@ -269,22 +269,35 @@ try_mount ()
 	dev="${1}"
 	mountp="${2}"
 	opts="${3}"
+	fstype="${4}"
 
 	old_mountp="$(where_is_mounted ${dev})"
 
 	if [ -n "${old_mountp}" ]
 	then
-		mount -n -o remount,"${opts}" "${dev}" "${old_mountp}" || panic "Remounting ${dev} ${opts} on ${old_mountp} failed"
-		mount -n -o bind "${old_mountp}" "${mountp}" || panic "Cannot bind-mount ${old_mountp} on ${mountp}"
+		if [ "${opts}" != "ro" ]
+		then
+			mount -o remount,"${opts}" "${dev}" "${old_mountp}" || panic "Remounting ${dev} ${opts} on ${old_mountp} failed"
+		fi
+
+		mount -o bind "${old_mountp}" "${mountp}" || panic "Cannot bind-mount ${old_mountp} on ${mountp}"
 	else
-		mount -n -t $(get_fstype "${dev}") -o "${opts}" "${dev}" "${mountp}" || panic "Cannot mount ${dev} on ${mountp}"
+		if [ -z "${fstype}" ]
+		then
+			fstype=$(get_fstype "${dev}")
+		fi
+		mount -t "${fstype}" -o "${opts}" "${dev}" "${mountp}" || panic "Cannot mount ${dev} on ${mountp}, fstype=${fstype}, options=${opts}"
 	fi
 }
 
 find_cow_device ()
 {
+	# Returns a device containing a partition labeled "${pers_label}" or containing a file named the same way
+	#  in the latter case the partition containing the file is left mounted
+	#  if is not in black_listed_devices
 	pers_label="${1}"
 	cow_backing="/${pers_label}-backing"
+	black_listed_devices="${2}"
 
 	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v fd)
 	do
@@ -292,16 +305,32 @@ find_cow_device ()
 		do
 			devname=$(sys2dev "${dev}")
 
+			if echo "${black_listed_devices}" | grep -q "${devname}"
+			then
+				# skip this device enterely
+				break
+			fi
+
 			if [ "$(/lib/udev/vol_id -l ${devname} 2>/dev/null)" = "${pers_label}" ]
 			then
 				echo "${devname}"
 				return
 			fi
 
+			if [ "${PERSISTENT}" = "nofiles" ]
+			then
+				# do not mount the device to find for image files
+				# just skip this
+				break
+			fi
+
 			case "$(get_fstype ${devname})" in
 				vfat|ext2|ext3|jffs2)
 					mkdir -p "${cow_backing}"
-					try_mount "${devname}" "${cow_backing}" "rw"
+					if ! try_mount "${devname}" "${cow_backing}" "rw"
+					then
+						break
+					fi
 
 					if [ -f "${cow_backing}/${pers_label}" ]
 					then
@@ -320,11 +349,12 @@ find_cow_device ()
 
 find_files ()
 {
-	# return the first of ${filenames} found on vfat and ext2/ext3 devices
+	# return the a string composed by device name, mountpoint an the first of ${filenames} found on a supported partition
 	# FIXME: merge with above function
 
 	filenames="${1}"
 	snap_backing="/snap-backing"
+	black_listed_devices="${2}"
 
 	for sysblock in $(echo /sys/block/* | tr ' ' '\n' | grep -v loop | grep -v ram | grep -v fd)
 	do
@@ -333,19 +363,28 @@ find_files ()
 			devname=$(sys2dev "${dev}")
 			devfstype="$(get_fstype ${devname})"
 
+			if echo "${black_listed_devices}" | grep -q "${devname}"
+			then
+				# skip this device enterely
+				break
+			fi
+
 			if is_supported_fs ${devfstype}
 			then
 				mkdir -p "${snap_backing}"
-				try_mount "${devname}" "${snap_backing}" "ro"
 
-				for filename in ${filenames}
+				if try_mount "${devname}" "${snap_backing}" "ro" "${devfstype}"
+				then
+					for filename in ${filenames}
 					do
-					if [ -f "${snap_backing}/${filename}" ]
-					then
-						echo "${devname} ${snap_backing} ${filename}"
-						return 0
-					fi
-				done
+						if [ -f "${snap_backing}/${filename}" ]
+						then
+							echo "${devname} ${snap_backing} ${filename}"
+							umount ${snap_backing}
+							return 0
+						fi
+					done
+				fi
 
 				umount ${snap_backing}
 			fi
