Avoiding using busybox cpio applet, this should fix snapshot restore.

diff --git a/scripts/live b/scripts/live
--- a/scripts/live
+++ b/scripts/live
@@ -992,9 +992,9 @@ try_snap ()
 				cpioargs='--unconditional --make-directories'
 			fi
 
-			if ! (cd "${snap_mount}" && zcat "${snapback}/${snapfile}" | cpio $cpioargs --extract --preserve-modification-time --no-absolute-filenames --sparse 2>/dev/null)
+			if ! (cd "${snap_mount}" && zcat "${snapback}/${snapfile}" | $cpiopath $cpioargs --extract --preserve-modification-time --no-absolute-filenames --sparse 2>/dev/null)
 			then
-				log_warning_msg "failure to \"zcat ${snapback}/${snapfile} | cpio $cpioargs --extract --preserve-modification-time --no-absolute-filenames --sparse\""
+				log_warning_msg "failure to \"zcat ${snapback}/${snapfile} | $cpiopath $cpioargs --extract --preserve-modification-time --no-absolute-filenames --sparse\""
 			fi
 		fi
 
