Adding upstream version 1.107.1.

diff --git a/scripts/live b/scripts/live
--- a/scripts/live
+++ b/scripts/live
@@ -36,7 +36,7 @@ Arguments ()
 {
 	PRESEEDS=""
 
-	for ARGUMENT in `cat /proc/cmdline`
+	for ARGUMENT in $(cat /proc/cmdline)
 	do
 		case "${ARGUMENT}" in
 			access=*)
@@ -314,14 +314,14 @@ Arguments ()
 
 				mkdir -p /root/var/run/network
 				chroot /root ifup -a
-				chroot /root wget -P /tmp "$location"
+				chroot /root wget -P /tmp "${location}"
 				chroot /root ifdown -a
 
 				umount /root/sys
 				umount /root/proc
 				umount /root/dev
 
-				LOCATION="/tmp/$(basename "$location")"
+				LOCATION="/tmp/$(basename "${location}")"
 				;;
 
 			*/*=*)
@@ -334,6 +334,11 @@ Arguments ()
 			showmounts)
 				SHOWMOUNTS="Yes"
 				export SHOWMOUNTS
+				;;
+
+			textonly)
+				TEXTONLY="Yes"
+				export TEXTONLY
 				;;
 
 			timezone=*)
@@ -419,7 +424,7 @@ is_live_path ()
 	then
 		for FILESYSTEM in squashfs ext2 ext3 xfs dir
 		do
-			if [ "`echo ${DIRECTORY}/${LIVE_MEDIA_PATH}/*.${FILESYSTEM}`" != "${DIRECTORY}/${LIVE_MEDIA_PATH}/*.${FILESYSTEM}" ]
+			if [ "$(echo ${DIRECTORY}/${LIVE_MEDIA_PATH}/*.${FILESYSTEM})" != "${DIRECTORY}/${LIVE_MEDIA_PATH}/*.${FILESYSTEM}" ]
 			then
 				return 0
 			fi
@@ -431,9 +436,9 @@ is_live_path ()
 
 get_backing_device ()
 {
-	case "$1" in
+	case "${1}" in
 		*.squashfs|*.ext2|*.ext3)
-			echo $(setup_loop "$1" "loop" "/sys/block/loop*" '0' "${LIVE_MEDIA_ENCRYPTION}")
+			echo $(setup_loop "${1}" "loop" "/sys/block/loop*" '0' "${LIVE_MEDIA_ENCRYPTION}")
 			;;
 
 		*.dir)
@@ -441,17 +446,17 @@ get_backing_device ()
 			;;
 
 		*)
-			panic "Unrecognized live filesystem: $1"
+			panic "Unrecognized live filesystem: ${1}"
 			;;
 	esac
 }
 
 match_files_in_dir ()
 {
-	# Does any files match pattern $1 ?
-	local pattern="$1"
+	# Does any files match pattern ${1} ?
+	local pattern="${1}"
 
-	if [ "$(echo $pattern)" != "$pattern" ]
+	if [ "$(echo ${pattern})" != "${pattern}" ]
 	then
 		return 0
 	fi
@@ -461,15 +466,15 @@ match_files_in_dir ()
 
 mount_images_in_directory ()
 {
-	directory="$1"
-	rootmnt="$2"
+	directory="${1}"
+	rootmnt="${2}"
 
-	if match_files_in_dir "$directory/${LIVE_MEDIA_PATH}/*.squashfs" ||
-		match_files_in_dir "$directory/${LIVE_MEDIA_PATH}/*.ext2" ||
-		match_files_in_dir "$directory/${LIVE_MEDIA_PATH}/*.ext3" ||
-		match_files_in_dir "$directory/${LIVE_MEDIA_PATH}/*.dir"
+	if match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.squashfs" ||
+		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.ext2" ||
+		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.ext3" ||
+		match_files_in_dir "${directory}/${LIVE_MEDIA_PATH}/*.dir"
 	then
-		setup_unionfs "$directory/${LIVE_MEDIA_PATH}" "$rootmnt"
+		setup_unionfs "${directory}/${LIVE_MEDIA_PATH}" "${rootmnt}"
 	else
 		:
 	fi
@@ -517,7 +522,7 @@ copy_live_to ()
 		then
 			size=$( expr $(ls -la ${MODULETORAMFILE} | awk '{print $5}') / 1024 + 5000 )
 		else
-			log_warning_msg "Error: toram-module $MODULETORAM ($MODULETORAMFILE) could not be read."
+			log_warning_msg "Error: toram-module ${MODULETORAM} (${MODULETORAMFILE}) could not be read."
 			return 1
 		fi
 	fi
@@ -546,7 +551,7 @@ copy_live_to ()
 
 	if [ "${freespace}" -lt "${size}" ]
 	then
-		[ "$quiet" != "y" ] && log_warning_msg "Not enough free ${free_string} (${freespace}k free, ${size}k needed) to copy live media in ${copytodev}."
+		[ "${quiet}" != "y" ] && log_warning_msg "Not enough free ${free_string} (${freespace}k free, ${size}k needed) to copy live media in ${copytodev}."
 		return 1
 	fi
 
@@ -555,7 +560,7 @@ copy_live_to ()
 	echo "mount -t ${fstype} ${mount_options} ${dev} ${copyto}"
 	mount -t "${fstype}" ${mount_options} "${dev}" "${copyto}"
 
-	if [ "$extension" = "tgz" ]
+	if [ "${extension}" = "tgz" ]
 	then
 		cd "${copyto}"
 		tar zxf "${copyfrom}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
@@ -591,9 +596,9 @@ do_netmount ()
 	ipconfig ${DEVICE} | tee /netboot.config
 
 	# source relevant ipconfig output
-	OLDHOSTNAME=$HOSTNAME
+	OLDHOSTNAME=${HOSTNAME}
 	. /tmp/net-${DEVICE}.conf
-	[ -z $HOSTNAME ] && HOSTNAME=$OLDHOSTNAME
+	[ -z ${HOSTNAME} ] && HOSTNAME=${OLDHOSTNAME}
 	export HOSTNAME
 
 	if [ "${NFSROOT}" = "auto" ]
@@ -607,12 +612,12 @@ do_netmount ()
 		return ${rc}
 	fi
 
-	if [ "${NFSROOT#*:}" = "$NFSROOT" ] && [ "$NETBOOT" != "cifs" ]
+	if [ "${NFSROOT#*:}" = "${NFSROOT}" ] && [ "$NETBOOT" != "cifs" ]
 	then
 		NFSROOT=${ROOTSERVER}:${NFSROOT}
 	fi
 
-	[ "$quiet" != "y" ] && log_begin_msg "Trying netboot from ${NFSROOT}"
+	[ "${quiet}" != "y" ] && log_begin_msg "Trying netboot from ${NFSROOT}"
 
 	if [ "${NETBOOT}" != "nfs" ] && do_cifsmount
 	then
@@ -624,26 +629,26 @@ do_netmount ()
 		rc=0
 	fi
 
-	[ "$quiet" != "y" ] && log_end_msg
+	[ "${quiet}" != "y" ] && log_end_msg
 	return ${rc}
 }
 
 do_httpmount ()
 {
 	rc=1
-	extension=`echo "${FETCH}" | sed 's/\(.*\)\.\(.*\)/\2/'`
+	extension=$(echo "${FETCH}" | sed 's/\(.*\)\.\(.*\)/\2/')
 
 	case "${extension}" in
 		squashfs|tgz|tar)
-			[ "$quiet" != "y" ] && log_begin_msg "Trying wget ${FETCH} -O ${mountpoint}/$(basename ${FETCH})"
+			[ "${quiet}" != "y" ] && log_begin_msg "Trying wget ${FETCH} -O ${mountpoint}/$(basename ${FETCH})"
 			mkdir -p "${mountpoint}/${LIVE_MEDIA_PATH}"
 			wget "${FETCH}" -O "${mountpoint}/${LIVE_MEDIA_PATH}/$(basename ${FETCH})"
-			[ $? -eq 0 ] && rc=0
-			[ "${extension}" == "tgz" ] && live_dest="ram"
+			[ ${?} -eq 0 ] && rc=0
+			[ "${extension}" = "tgz" ] && live_dest="ram"
 			;;
 
 		*)
-			[ "$quiet" != "y" ] && log_begin_msg "Unrecognized archive extension for ${FETCH}"
+			[ "${quiet}" != "y" ] && log_begin_msg "Unrecognized archive extension for ${FETCH}"
 	esac
 
 	return ${rc}
@@ -660,7 +665,7 @@ do_nfsmount ()
 		NFSOPTS=""
 	fi
 
-	[ "$quiet" != "y" ] && log_begin_msg "Trying nfsmount -o nolock -o ro ${NFSOPTS} ${NFSROOT} ${mountpoint}"
+	[ "${quiet}" != "y" ] && log_begin_msg "Trying nfsmount -o nolock -o ro ${NFSOPTS} ${NFSROOT} ${mountpoint}"
 
 	# FIXME: This for loop is an ugly HACK round an nfs bug
 	for i in 0 1 2 3 4 5 6 7 8 9 a b c d e f 10 11 12 13
@@ -685,7 +690,7 @@ do_cifsmount ()
 			CIFSOPTS="${NFSOPTS}"
 		fi
 
-		[ "$quiet" != "y" ] && log_begin_msg "Trying mount.cifs ${NFSROOT} ${mountpoint} ${CIFSOPTS}"
+		[ "${quiet}" != "y" ] && log_begin_msg "Trying mount.cifs ${NFSROOT} ${mountpoint} ${CIFSOPTS}"
 		modprobe "${MP_QUIET}" cifs
 
 		if mount.cifs "${NFSROOT}" "${mountpoint}" "${CIFSOPTS}"
@@ -727,7 +732,7 @@ do_snap_copy ()
 		if [ -n "${fstype}" ]
 		then
 			# Copying stuff...
-			mount -t "${fstype}" -o ro "${fromdev}" "${tomount}"
+			mount -t "${fstype}" -o ro,noatime "${fromdev}" "${tomount}"
 			cp -a "${tomount}"/* ${todir}
 			umount "${tomount}"
 		else
@@ -745,13 +750,13 @@ do_snap_copy ()
 	else
 		return 1
 
-		[ "$quiet" != "y" ] && log_warning_msg "Unable to find the snapshot ${snap_type} medium"
+		[ "${quiet}" != "y" ] && log_warning_msg "Unable to find the snapshot ${snap_type} medium"
 	fi
 }
 
 try_snap ()
 {
-	# Look for $snap_label.* in block devices and copy the contents to $snap_mount
+	# Look for ${snap_label}.* in block devices and copy the contents to ${snap_mount}
 	# and remember the device and filename for resync on exit in live-initramfs.init
 
 	snap_label="${1}"
@@ -823,8 +828,8 @@ try_snap ()
 
 setup_unionfs ()
 {
-	image_directory="$1"
-	rootmnt="$2"
+	image_directory="${1}"
+	rootmnt="${2}"
 
 	modprobe "${MP_QUIET}" -b ${UNIONTYPE}
 
@@ -838,7 +843,7 @@ setup_unionfs ()
 	# Let's just mount the read-only file systems first
 	rofsstring=""
 	rofslist=""
-	minor_kernel_version=`uname -r|cut -c 5-|sed 's/[^0-9].*//'`
+	minor_kernel_version=$(uname -r|cut -c 5-|sed 's/[^0-9].*//')
 
 	if [ "${NETBOOT}" = "nfs" ] && [ "${minor_kernel_version}" -lt 22 ]
 	then
@@ -851,15 +856,15 @@ setup_unionfs ()
 	# Read image names from ${MODULE}.module if it exists
 	if [ -e "${image_directory}/filesystem.${MODULE}.module" ]
 	then
-		for IMAGE in `cat ${image_directory}/filesystem.${MODULE}.module`
+		for IMAGE in $(cat ${image_directory}/filesystem.${MODULE}.module)
 		do
-			image_string="${image_string} ${image_directory}/${image}"
+			image_string="${image_string} ${image_directory}/${IMAGE}"
 		done
 	elif [ -e "${image_directory}/${MODULE}.module" ]
 	then
-		for IMAGE in `cat ${image_directory}/${MODULE}.module`
+		for IMAGE in $(cat ${image_directory}/${MODULE}.module)
 		do
-			image_string="${image_string} ${image_directory}/${image}"
+			image_string="${image_string} ${image_directory}/${IMAGE}"
 		done
 	else
 		# ${MODULE}.module does not exist, create a list of images
@@ -875,7 +880,7 @@ setup_unionfs ()
 		done
 
 		# Now sort the list
-		image_string="`echo ${image_string} | sed -e 's/ /\n/g' | sort `"
+		image_string="$(echo ${image_string} | sed -e 's/ /\n/g' | sort )"
 	fi
 
 	[ -n "${MODULETORAMFILE}" ] && image_string="${image_directory}/$(basename ${MODULETORAMFILE})"
@@ -893,7 +898,7 @@ setup_unionfs ()
 			rofslist="${image} ${rofslist}"
 		elif [ -f "${image}" ]
 		then
-			backdev=$(get_backing_device "$image")
+			backdev=$(get_backing_device "${image}")
 			fstype=$(get_fstype "${backdev}")
 
 			if [ "${fstype}" = "unknown" ]
@@ -902,8 +907,8 @@ setup_unionfs ()
 			fi
 
 			mkdir -p "${croot}/${imagename}"
-			echo "debug: Can not mount backdev $backdev (image = $image) on croot/imagename ${croot}/${imagename}"
-			mount -t "${fstype}" -o ro "${backdev}" "${croot}/${imagename}" || panic "Can not mount $backdev ($image) on ${croot}/${imagename}" && rofsstring="${croot}/${imagename}=${roopt}:${rofsstring}" && rofslist="${croot}/${imagename} ${rofslist}"
+			echo "debug: Can not mount backdev ${backdev} (image = ${image}) on croot/imagename ${croot}/${imagename}"
+			mount -t "${fstype}" -o ro,noatime "${backdev}" "${croot}/${imagename}" || panic "Can not mount ${backdev} (${image}) on ${croot}/${imagename}" && rofsstring="${croot}/${imagename}=${roopt}:${rofsstring}" && rofslist="${croot}/${imagename} ${rofslist}"
 		fi
 	done
 
@@ -923,13 +928,13 @@ setup_unionfs ()
 			cowdevice=${cowprobe}
 			cow_fstype=$(get_fstype "${cowprobe}")
 		else
-			[ "$quiet" != "y" ] && log_warning_msg "Unable to find the persistent medium"
+			[ "${quiet}" != "y" ] && log_warning_msg "Unable to find the persistent medium"
 		fi
 	fi
 
-	mount ${cowdevice} -t ${cow_fstype} -o rw /cow || panic "Can not mount $cowdevice on /cow"
+	mount ${cowdevice} -t ${cow_fstype} -o rw,noatime /cow || panic "Can not mount ${cowdevice} on /cow"
 
-	mount -t ${UNIONTYPE} -o dirs=/cow=rw:$rofsstring ${UNIONTYPE} "$rootmnt" || panic "${UNIONTYPE} mount failed"
+	mount -t ${UNIONTYPE} -o noatime,dirs=/cow=rw:${rofsstring} ${UNIONTYPE} "${rootmnt}" || panic "${UNIONTYPE} mount failed"
 
 	# Adding other custom mounts
 	if [ -n "${PERSISTENT}" ]
@@ -940,10 +945,10 @@ setup_unionfs ()
 
 		if [ -b "${homecow}" ]
 		then
-			mount -t $(get_fstype "${homecow}") -o rw "${homecow}" "${rootmnt}/home"
+			mount -t $(get_fstype "${homecow}") -o rw,noatime "${homecow}" "${rootmnt}/home"
 			export HOMEMOUNTED=1 # used to proper calculate free space in do_snap_copy()
 		else
-			[ "$quiet" != "y" ] && log_warning_msg "Unable to find the persistent home medium"
+			[ "${quiet}" != "y" ] && log_warning_msg "Unable to find the persistent home medium"
 		fi
 
 		# Look for other snapshots to copy in
@@ -971,7 +976,7 @@ setup_unionfs ()
 
 	# shows cow fs on /cow for use by live-snapshot
 	mkdir -p "${rootmnt}/live/cow"
-	mount -o bind /cow "${rootmnt}/live/cow"
+	mount -o move /cow "${rootmnt}/live/cow"
 }
 
 check_dev ()
@@ -994,14 +999,14 @@ check_dev ()
 
 	if is_supported_fs ${fstype}
 	then
-		mount -t ${fstype} -o ro "${devname}" $mountpoint || continue
+		mount -t ${fstype} -o ro,noatime "${devname}" ${mountpoint} || continue
 
-		if is_live_path $mountpoint
+		if is_live_path ${mountpoint}
 		then
-			echo $mountpoint
+			echo ${mountpoint}
 			return 0
 		else
-			umount $mountpoint
+			umount ${mountpoint}
 		fi
 	fi
 
@@ -1098,10 +1103,10 @@ mountroot ()
 	Arguments
 
 	set_usplash_timeout
-	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/live-premount"
+	[ "${quiet}" != "y" ] && log_begin_msg "Running /scripts/live-premount"
 	pulsate
 	run_scripts /scripts/live-premount
-	[ "$quiet" != "y" ] && log_end_msg
+	[ "${quiet}" != "y" ] && log_end_msg
 
 	# Needed here too because some things (*cough* udev *cough*)
 	# changes the timeout
@@ -1120,7 +1125,7 @@ mountroot ()
 		# Scan local devices for the image
 		for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19
 		do
-			livefs_root=$(find_livefs $i)
+			livefs_root=$(find_livefs ${i})
 
 			if [ -n "${livefs_root}" ]
 			then
@@ -1153,7 +1158,7 @@ mountroot ()
 
 	if [ -n "${MODULETORAMFILE}" ]
 	then
-		setup_unionfs "${livefs_root}" "$rootmnt"
+		setup_unionfs "${livefs_root}" "${rootmnt}"
 	else
 		mount_images_in_directory "${livefs_root}" "${rootmnt}"
 	fi
@@ -1161,11 +1166,11 @@ mountroot ()
 	log_end_msg
 
 	maybe_break live-bottom
-	[ "$quiet" != "y" ] && log_begin_msg "Running /scripts/live-bottom"
+	[ "${quiet}" != "y" ] && log_begin_msg "Running /scripts/live-bottom"
 
 	pulsate
 	run_scripts /scripts/live-bottom
-	[ "$quiet" != "y" ] && log_end_msg
+	[ "${quiet}" != "y" ] && log_end_msg
 
 	exec 1>&6 6>&-
 	exec 2>&7 7>&-
