Adding upstream version 1.173.1.

diff --git a/scripts/live-helpers b/scripts/live-helpers
--- a/scripts/live-helpers
+++ b/scripts/live-helpers
@@ -76,25 +76,17 @@ is_supported_fs ()
 
 get_fstype ()
 {
-	local FSTYPE
-	local FSSIZE
-
-	# fstype misreports LUKS devices
-	if is_luks "${1}"
+	# udev >=146-1 no longer provides vol_id:
+	if [ -x /lib/udev/vol_id ]
 	then
-	    /lib/udev/vol_id -t ${1} 2>/dev/null
-	    return
+		/lib/udev/vol_id -t ${1} 2>/dev/null
+	else
+		eval $(blkid -o udev "${1}")
+		if [ -n "$ID_FS_TYPE" ]
+		then
+			echo "${ID_FS_TYPE}"
+		fi
 	fi
-
-	eval $(fstype ${1} 2>/dev/null)
-
-	if [ "${FSTYPE}" != "unknown" ]
-	then
-		echo ${FSTYPE}
-		return 0
-	fi
-
-	/lib/udev/vol_id -t ${1} 2>/dev/null
 }
 
 where_is_mounted ()
@@ -295,7 +287,8 @@ try_mount ()
 		then
 			fstype=$(get_fstype "${dev}")
 		fi
-		mount -t "${fstype}" -o "${opts}" "${dev}" "${mountp}" || panic "Cannot mount ${dev} on ${mountp}, fstype=${fstype}, options=${opts}"
+		mount -t "${fstype}" -o "${opts}" "${dev}" "${mountp}" || \
+		( echo "SKIPPING: Cannot mount ${dev} on ${mountp}, fstype=${fstype}, options=${opts}" > live.log && return 0 )
 	fi
 }
 
@@ -357,10 +350,21 @@ find_cow_device ()
 				done
 			fi
 
-			if [ "$(/lib/udev/vol_id -l ${devname} 2>/dev/null)" = "${pers_label}" ]
+			# udev >=146-1 no longer provides vol_id:
+			if [ -x /lib/udev/vol_id ]
 			then
-				echo "${devname}"
-				return 0
+				if [ "$(/lib/udev/vol_id -l ${devname} 2>/dev/null)" = "${pers_label}" ]
+				then
+					echo "${devname}"
+					return 0
+				fi
+			else
+				eval $(blkid -o udev "${devname}")
+				if [ "$ID_FS_LABEL" = "${pers_label}" ]
+				then
+					echo "${devname}"
+					return 0
+				fi
 			fi
 
 			if [ "${PERSISTENT}" = "nofiles" ]
@@ -373,17 +377,15 @@ find_cow_device ()
 			case "$(get_fstype ${devname})" in
 				vfat|ext2|ext3|ext4|jffs2)
 					mkdir -p "${cow_backing}"
-					if ! try_mount "${devname}" "${cow_backing}" "rw"
+					if try_mount "${devname}" "${cow_backing}" "rw"
 					then
-						break
-					fi
-
-					if [ -f "${pers_fpath}" ]
-					then
-						echo $(setup_loop "${pers_fpath}" "loop" "/sys/block/loop*")
-						return 0
-					else
-						umount ${cow_backing}
+						if [ -f "${pers_fpath}" ]
+						then
+							echo $(setup_loop "${pers_fpath}" "loop" "/sys/block/loop*")
+							return 0
+						else
+							umount ${cow_backing} > /dev/null 2>&1 || true
+						fi
 					fi
 					;;
 				*)
